// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa377swv7I7IDgyekY_s2PGCYkRbOJYWM',
    appId: '1:934195979899:android:67cad3fd77cd6aa80564de',
    messagingSenderId: '934195979899',
    projectId: 'video-chat-app-de78c',
    storageBucket: 'video-chat-app-de78c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsvrW7mOksSlILHJoQ0s5yOm3PLN3CwWU',
    appId: '1:934195979899:ios:dd508344d91410a00564de',
    messagingSenderId: '934195979899',
    projectId: 'video-chat-app-de78c',
    storageBucket: 'video-chat-app-de78c.firebasestorage.app',
    iosBundleId: 'com.vid.videoChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdyURiMOIVzEHCQrSLk42i_xMsw-rHiRc',
    appId: '1:934195979899:web:1b102354d6d5848f0564de',
    messagingSenderId: '934195979899',
    projectId: 'video-chat-app-de78c',
    authDomain: 'video-chat-app-de78c.firebaseapp.com',
    storageBucket: 'video-chat-app-de78c.firebasestorage.app',
    measurementId: 'G-CG8342YHPZ',
  );

}